CREATE TABLE USERS( ID VARCHAR2, FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, PRIME VARCHAR2);
INSERT INTO USERS VALUES ('1','Cody','Sanders','N');
INSERT INTO USERS VALUES ('2','Kent','Beck','Y');
INSERT INTO USERS VALUES ('3','Ross','Mason','Y');

